apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-vpc-block-retain-10iops-tier
provisioner: vpc.block.csi.ibm.io
parameters:
  profile: "10iops-tier"              # The VPC Storage profile used.
  # iopsPerGB: "10"                   # The IOPS per Gigabyte that is supported for this profile. This is just for the user info.
  sizeRange: "[10-2000]GiB"           # The size range in GiB that is supported. The user will specify a size on the PVC
  csi.storage.k8s.io/fstype: "ext4"   # ext4 is the default filesytem used. The user can override this default
  billingType: "hourly"               # The default billing policy used. The uer can override this default
  encrypted: "false"                  # By default, all PVC using this class will only be provider managed encrypted. The user can override this default
  encryptionKey: ""                   # If encrypted is true, then a user must specify the encryption key used associated KP instance
  resourceGroup: ""                   # Use resource group if specified here. else use the one mentioned in storage-secrete-store
  region: ""                        # (applicable only for dev/prestage/stage) By default, the storage vpc driver will select a region. The user can override this default
  zone: ""                            # By default, the storage vpc driver will select a zone. The user can override this default
  tags: ""                            # A list of tags "a, b, c" that will be created when the volume is created. This can be overidden by user
  classVersion: "1"
reclaimPolicy: "Retain"
