kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ibm-vpc-block-csi-controller
spec:
  template:
    spec:
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.0.2
        - name: csi-attacher
          image:  registry.k8s.io/sig-storage/csi-attacher:v4.6.1
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/csi-attacher:v2.13.1
        - name: iks-vpc-block-driver
          imagePullPolicy: Always
          image: gcr.io/k8s-staging-cloud-provider-ibm/ibm-vpc-block-csi-driver:master
        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v1.11.2
        - name: csi-snapshotter
          image: registry.k8s.io/sig-storage/csi-snapshotter:v8.0.1
