kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ibm-vpc-block-csi-node
spec:
  template:
    spec:
      containers:
        - name: iks-vpc-block-node-driver
          imagePullPolicy: Always
          image: gcr.io/k8s-staging-cloud-provider-ibm/ibm-vpc-block-csi-driver:master
        - name: csi-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.2.0
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.3.0
