apiVersion: v1
data:
  slclient.toml: REPLACE_ME 
kind: Secret
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: ibm-vpc-block-csi-driver
    kubernetes.io/cluster-service: "true"
  name: storage-secret-store
  namespace: kube-system
type: Opaque
